# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractinput',
            name='parameter_type',
            field=models.CharField(blank=True, choices=[(b'text', b'Single line'), (b'password', b'Password'), (b'textarea', b'Multi line text'), (b'select', b'Select box'), (b'checkbox', b'Checkbox'), (b'file', b'File'), (b'bigfile', b'File')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='input',
            name='parameter_type',
            field=models.CharField(blank=True, choices=[(b'text', b'Single line'), (b'textarea', b'Multi line text'), (b'select', b'Select box'), (b'file', b'File field'), (b'bigfile', b'Big file field'), (b'checkbox', b'Checkbox')], max_length=50, null=True),
        ),
    ]
