# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 11:07


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_auto_20160823_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractinput',
            name='parameter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='abstractinput',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='input',
            name='parameter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='input',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
