# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 08:11


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_auto_20160825_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='interaction_finished',
            field=models.BooleanField(default=False),
        ),
    ]
