# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-09 14:33


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_widget_interaction_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('inp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input', to='workflows.AbstractInput')),
                ('out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output', to='workflows.AbstractOutput')),
            ],
        ),
    ]
