# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-12-18 07:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import workflows.thumbs


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0009_auto_20171219_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='copy_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='abstractinput',
            name='multi',
            field=models.BooleanField(default=False, help_text='Inputs with this flag set will behave like this: whenever a connection is added to this input another input will be created on the fly that accepts the same data. In the action function, this will be represented as a list.'),
        ),
        migrations.AlterField(
            model_name='abstractinput',
            name='parameter_type',
            field=models.CharField(blank=True, choices=[('text', 'Single line'), ('password', 'Password'), ('textarea', 'Multi line text'), ('select', 'Select box'), ('checkbox', 'Checkbox'), ('file', 'File'), ('bigfile', 'File')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='abstractinput',
            name='uid',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='abstractinput',
            name='variable',
            field=models.CharField(help_text='The variable attribute of both the input and the output are important because this is how the data will be accessed in the python function that is executed when the widget runs.', max_length=50),
        ),
        migrations.AlterField(
            model_name='abstractoption',
            name='uid',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=250),
        ),
        migrations.AlterField(
            model_name='abstractoutput',
            name='uid',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='abstractoutput',
            name='variable',
            field=models.CharField(help_text='The variable attribute of both the input and the output are important because this is how the data will be accessed in the python function that is executed when the widget runs.', max_length=50),
        ),
        migrations.AlterField(
            model_name='abstractwidget',
            name='action',
            field=models.CharField(help_text='Action is the name of a python function that will be called when the widget is executed.', max_length=200),
        ),
        migrations.AlterField(
            model_name='abstractwidget',
            name='category',
            field=models.ForeignKey(help_text='Category determines to which category this widget belongs. Categories can be nested.', on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='workflows.Category'),
        ),
        migrations.AlterField(
            model_name='abstractwidget',
            name='description',
            field=models.TextField(blank=True, help_text='Description is used for a human readable description of what a widget does. A user will see this when he right clicks the widget and clicks help.'),
        ),
        migrations.AlterField(
            model_name='abstractwidget',
            name='has_progress_bar',
            field=models.BooleanField(default=False, help_text='The flag has progress bar determines if the widget implements a progress bar.'),
        ),
        migrations.AlterField(
            model_name='abstractwidget',
            name='image',
            field=workflows.thumbs.ThumbnailField(blank=True, help_text='Image and Treeview image are deprecated and will be phased out soon. Please use the static image field.', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='abstractwidget',
            name='interaction_view',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='abstractwidget',
            name='interactive',
            field=models.BooleanField(default=False, help_text='The widget can be interactive. This means that when a user executes the widget, the action will perform, then the interaction view will be executed and finally the Post interact action will be executed.'),
        ),
        migrations.AlterField(
            model_name='abstractwidget',
            name='is_streaming',
            field=models.BooleanField(default=False, help_text='The is streaming flag is currently under construction, please do not use it yet.'),
        ),
        migrations.AlterField(
            model_name='abstractwidget',
            name='name',
            field=models.CharField(help_text='Name is the name that will be displayed in the widget repository and under the actual widget itself.', max_length=200),
        ),
        migrations.AlterField(
            model_name='abstractwidget',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='The Order determines the order in which the widget will be displayed in the repository. This is set automatically when sorting widgets in a single category from the admin.'),
        ),
        migrations.AlterField(
            model_name='abstractwidget',
            name='package',
            field=models.CharField(blank=True, default='', help_text='Package is the package name. You are encouraged to use packages.', max_length=150),
        ),
        migrations.AlterField(
            model_name='abstractwidget',
            name='post_interact_action',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='abstractwidget',
            name='static_image',
            field=models.CharField(blank=True, default='', help_text='In the static image field just enter the filename of the image (without the path). The path will be $package_name$/icons/widget/$filename$ and $package_name$/icons/treeview/$filename$ where the treeview image is the small image that appears in the treeview on the left side and the widget image is the actual normal sized icon for the widget. IMPORTANT: the static image field only works if the package is set.', max_length=250),
        ),
        migrations.AlterField(
            model_name='abstractwidget',
            name='streaming_visualization_view',
            field=models.CharField(blank=True, default='', help_text='Visualization view is (like the action) a python function that is a view that will render a template.', max_length=200),
        ),
        migrations.AlterField(
            model_name='abstractwidget',
            name='treeview_image',
            field=workflows.thumbs.ThumbnailField(blank=True, null=True, upload_to='treeview'),
        ),
        migrations.AlterField(
            model_name='abstractwidget',
            name='uid',
            field=models.CharField(blank=True, default='', help_text='UID is set automatically when you export a package with the -u switch.', max_length=250),
        ),
        migrations.AlterField(
            model_name='abstractwidget',
            name='user',
            field=models.ForeignKey(blank=True, help_text='If the User field is blank, everyone will see the widget, otherwise just this user. This is mainly used for Web Service imports as they are only visible to users that imported them.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='abstractwidget',
            name='visualization_view',
            field=models.CharField(blank=True, default='', help_text='Visualization view is (like the action) a python function that is a view that will render a template.', max_length=200),
        ),
        migrations.AlterField(
            model_name='abstractwidget',
            name='windows_queue',
            field=models.BooleanField(default=False, help_text="This is used for Matjaz Jursic's widgets."),
        ),
        migrations.AlterField(
            model_name='abstractwidget',
            name='wsdl',
            field=models.URLField(blank=True, help_text='WSDL and WSDL method are used if the widget is a call of a Web Service. Web Service widgets are usually not entered in the admin panel, but in the application itself by importing a Web Service.'),
        ),
        migrations.AlterField(
            model_name='abstractwidget',
            name='wsdl_method',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='uid',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='input',
            name='parameter_type',
            field=models.CharField(blank=True, choices=[('text', 'Single line'), ('textarea', 'Multi line text'), ('select', 'Select box'), ('file', 'File field'), ('bigfile', 'Big file field'), ('checkbox', 'Checkbox')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='type',
            field=models.CharField(choices=[('regular', 'Regular widget'), ('subprocess', 'Subprocess widget'), ('input', 'Input widget'), ('output', 'Output widget'), ('for_input', 'For input'), ('for_output', 'For output'), ('cv_input', 'Cross Validation input'), ('cv_output', 'Cross Validation output'), ('cv_input2', 'Cross Validation input 2'), ('cv_input3', 'Cross Validation input 3')], default='regular', max_length=50),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='name',
            field=models.CharField(default='Untitled workflow', max_length=200),
        ),
    ]
