# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-11-16 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0010_auto_20201218_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='creation_time',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='last_modified',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
