# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-11-16 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0011_auto_20221116_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
