
from django.test import TestCase
from workflows.models import Workflow

TEST_USERNAME = 'testuser'
TEST_PASSWORD = '123'

TEST_WORKFLOW_USERS_PK = 2


class WorkflowExportTest(TestCase):
    fixtures = ['test_data_api', ]

    def test_export_workflow(self):
        w = Workflow.objects.get(pk=2)
        a = w.export()
        b = {'connections': [{'input_id': 13, 'output_id': 7},
                             {'input_id': 15, 'output_id': 8},
                             {'input_id': 16, 'output_id': 9},
                             {'input_id': 14, 'output_id': 10},
                             {'input_id': 52, 'output_id': 16}],
             'description': 'Tole je opis.',
             'name': 'Multiply integers',
             'widgets': [{'abstract_widget': '8b20d4ad-c420-4156-973d-48d6d15934ba',
                          'abstract_widget_package': 'base',
                          'inputs': [{'description': '',
                                      'inner_output': None,
                                      'multi_id': 0,
                                      'name': 'Type your integer',
                                      'options': [],
                                      'order': 1,
                                      'outer_output': None,
                                      'parameter': True,
                                      'parameter_type': 'text',
                                      'pk': 10,
                                      'required': True,
                                      'short_name': 'int',
                                      'value': '5',
                                      'variable': 'integer'}],
                          'name': 'Create Integer',
                          'outputs': [{'description': 'The returned integer.',
                                       'inner_input': None,
                                       'name': 'Integer',
                                       'order': 1,
                                       'outer_input': None,
                                       'pk': 7,
                                       'short_name': 'int',
                                       'variable': 'integer'}],
                          'save_results': False,
                          'type': 'regular',
                          'workflow': None,
                          'x': 29,
                          'y': 77},
                         {'abstract_widget': '8b20d4ad-c420-4156-973d-48d6d15934ba',
                          'abstract_widget_package': 'base',
                          'inputs': [{'description': '',
                                      'inner_output': None,
                                      'multi_id': 0,
                                      'name': 'Type your integer',
                                      'options': [],
                                      'order': 1,
                                      'outer_output': None,
                                      'parameter': True,
                                      'parameter_type': 'text',
                                      'pk': 11,
                                      'required': True,
                                      'short_name': 'int',
                                      'value': '10',
                                      'variable': 'integer'}],
                          'name': 'Create Integer',
                          'outputs': [{'description': 'The returned integer.',
                                       'inner_input': None,
                                       'name': 'Integer',
                                       'order': 1,
                                       'outer_input': None,
                                       'pk': 8,
                                       'short_name': 'int',
                                       'variable': 'integer'}],
                          'save_results': False,
                          'type': 'regular',
                          'workflow': None,
                          'x': 40,
                          'y': 223},
                         {'abstract_widget': '8b20d4ad-c420-4156-973d-48d6d15934ba',
                          'abstract_widget_package': 'base',
                          'inputs': [{'description': '',
                                      'inner_output': None,
                                      'multi_id': 0,
                                      'name': 'Type your integer',
                                      'options': [],
                                      'order': 1,
                                      'outer_output': None,
                                      'parameter': True,
                                      'parameter_type': 'text',
                                      'pk': 12,
                                      'required': True,
                                      'short_name': 'int',
                                      'value': '5',
                                      'variable': 'integer'}],
                          'name': 'Create Integer',
                          'outputs': [{'description': 'The returned integer.',
                                       'inner_input': None,
                                       'name': 'Integer',
                                       'order': 1,
                                       'outer_input': None,
                                       'pk': 9,
                                       'short_name': 'int',
                                       'variable': 'integer'}],
                          'save_results': False,
                          'type': 'regular',
                          'workflow': None,
                          'x': 39,
                          'y': 364},
                         {'abstract_widget': 'c950af9c-be87-4761-a69e-e37f0c26cacb',
                          'abstract_widget_package': 'base',
                          'inputs': [{'description': '',
                                      'inner_output': None,
                                      'multi_id': 3,
                                      'name': 'Integers',
                                      'options': [],
                                      'order': 1,
                                      'outer_output': None,
                                      'parameter': False,
                                      'parameter_type': None,
                                      'pk': 13,
                                      'required': False,
                                      'short_name': 'int',
                                      'value': None,
                                      'variable': 'integers'},
                                     {'description': '',
                                      'inner_output': None,
                                      'multi_id': 3,
                                      'name': 'Integers',
                                      'options': [],
                                      'order': 2,
                                      'outer_output': None,
                                      'parameter': False,
                                      'parameter_type': None,
                                      'pk': 15,
                                      'required': False,
                                      'short_name': 'int',
                                      'value': None,
                                      'variable': 'integers'},
                                     {'description': '',
                                      'inner_output': None,
                                      'multi_id': 3,
                                      'name': 'Integers',
                                      'options': [],
                                      'order': 3,
                                      'outer_output': None,
                                      'parameter': False,
                                      'parameter_type': None,
                                      'pk': 16,
                                      'required': False,
                                      'short_name': 'int',
                                      'value': None,
                                      'variable': 'integers'},
                                     {'description': '',
                                      'inner_output': None,
                                      'multi_id': 3,
                                      'name': 'Integers',
                                      'options': [],
                                      'order': 4,
                                      'outer_output': None,
                                      'parameter': False,
                                      'parameter_type': None,
                                      'pk': 65,
                                      'required': False,
                                      'short_name': 'int',
                                      'value': None,
                                      'variable': 'integers'}],
                          'name': 'Multiply integers',
                          'outputs': [{'description': '',
                                       'inner_input': None,
                                       'name': 'Integer',
                                       'order': 1,
                                       'outer_input': None,
                                       'pk': 10,
                                       'short_name': 'int',
                                       'variable': 'integer'}],
                          'save_results': False,
                          'type': 'regular',
                          'workflow': None,
                          'x': 401,
                          'y': 144},
                         {'abstract_widget': '2c69b211-05fe-49a2-8de1-d38971e75b95',
                          'abstract_widget_package': 'base',
                          'inputs': [{'description': 'Displays the string so that it is readable.',
                                      'inner_output': None,
                                      'multi_id': 0,
                                      'name': 'String',
                                      'options': [],
                                      'order': 1,
                                      'outer_output': None,
                                      'parameter': False,
                                      'parameter_type': None,
                                      'pk': 14,
                                      'required': False,
                                      'short_name': 'str',
                                      'value': None,
                                      'variable': 'string'}],
                          'name': 'Display String',
                          'outputs': [],
                          'save_results': False,
                          'type': 'regular',
                          'workflow': None,
                          'x': 802,
                          'y': 111},
                         {'abstract_widget': '1b38bbab-7f89-4469-94cd-2f481f9c61f7',
                          'abstract_widget_package': 'base',
                          'inputs': [{'description': '',
                                      'inner_output': None,
                                      'multi_id': 0,
                                      'name': 'String',
                                      'options': [],
                                      'order': 1,
                                      'outer_output': None,
                                      'parameter': True,
                                      'parameter_type': 'textarea',
                                      'pk': 51,
                                      'required': False,
                                      'short_name': 'str',
                                      'value': 'balkb blalblab',
                                      'variable': 'string'}],
                          'name': 'Create String',
                          'outputs': [{'description': '',
                                       'inner_input': None,
                                       'name': 'String',
                                       'order': 1,
                                       'outer_input': None,
                                       'pk': 16,
                                       'short_name': 'str',
                                       'variable': 'string'}],
                          'save_results': False,
                          'type': 'regular',
                          'workflow': None,
                          'x': 272,
                          'y': 408},
                         {'abstract_widget': '9c8a4da5-6f43-4dbc-846c-adf280c0f484',
                          'abstract_widget_package': 'base',
                          'inputs': [{'description': '',
                                      'inner_output': None,
                                      'multi_id': 0,
                                      'name': 'String',
                                      'options': [],
                                      'order': 1,
                                      'outer_output': None,
                                      'parameter': False,
                                      'parameter_type': None,
                                      'pk': 52,
                                      'required': False,
                                      'short_name': 'str',
                                      'value': None,
                                      'variable': 'string'}],
                          'name': 'Word cloud',
                          'outputs': [],
                          'save_results': False,
                          'type': 'regular',
                          'workflow': None,
                          'x': 731,
                          'y': 283},
                         {'abstract_widget': None,
                          'inputs': [],
                          'name': 'Untitled widget',
                          'outputs': [{'description': '',
                                       'inner_input': 79,
                                       'name': 'Output',
                                       'order': 1,
                                       'outer_input': None,
                                       'pk': 23,
                                       'short_name': 'out',
                                       'variable': 'Output26'}],
                          'save_results': False,
                          'type': 'subprocess',
                          'workflow': {'connections': [],
                                       'description': '',
                                       'name': 'Untitled widget',
                                       'widgets': [{'abstract_widget': None,
                                                    'inputs': [{'description': None,
                                                                'inner_output': None,
                                                                'multi_id': 0,
                                                                'name': 'Output',
                                                                'options': [],
                                                                'order': 1,
                                                                'outer_output': 23,
                                                                'parameter': False,
                                                                'parameter_type': None,
                                                                'pk': 79,
                                                                'required': False,
                                                                'short_name': 'out',
                                                                'value': None,
                                                                'variable': 'Output26'}],
                                                    'name': 'Output',
                                                    'outputs': [],
                                                    'save_results': False,
                                                    'type': 'output',
                                                    'workflow': None,
                                                    'x': 364,
                                                    'y': 236}]},
                          'x': 443,
                          'y': 528},
                         {'abstract_widget': None,
                          'inputs': [],
                          'name': 'Untitled widget',
                          'outputs': [{'description': '',
                                       'inner_input': 97,
                                       'name': 'Output',
                                       'order': 1,
                                       'outer_input': None,
                                       'pk': 29,
                                       'short_name': 'out',
                                       'variable': 'Output32'}],
                          'save_results': False,
                          'type': 'subprocess',
                          'workflow': {'connections': [],
                                       'description': '',
                                       'name': 'Untitled widget',
                                       'widgets': [{'abstract_widget': None,
                                                    'inputs': [{'description': None,
                                                                'inner_output': None,
                                                                'multi_id': 0,
                                                                'name': 'Output',
                                                                'options': [],
                                                                'order': 1,
                                                                'outer_output': 29,
                                                                'parameter': False,
                                                                'parameter_type': None,
                                                                'pk': 97,
                                                                'required': False,
                                                                'short_name': 'out',
                                                                'value': None,
                                                                'variable': 'Output32'}],
                                                    'name': 'Output',
                                                    'outputs': [],
                                                    'save_results': False,
                                                    'type': 'output',
                                                    'workflow': None,
                                                    'x': 50,
                                                    'y': 150}]},
                          'x': 696,
                          'y': 417}]}

        self.assertEqual(a, b)
