
from django.test import TestCase
from workflows.models import Workflow

TEST_USERNAME = 'testuser'
TEST_PASSWORD = '123'

TEST_WORKFLOW_USERS_PK = 2


class WorkflowExportTest(TestCase):
    fixtures = ['test_data_api', ]

    def test_export_workflow(self):
        w = Workflow.objects.get(pk=2)
        a = w.export()
        b = {'connections': [{'input_id': 13, 'output_id': 7},
                             {'input_id': 15, 'output_id': 8},
                             {'input_id': 16, 'output_id': 9},
                             {'input_id': 14, 'output_id': 10},
                             {'input_id': 52, 'output_id': 16}],
             'description': u'Tole je opis.',
             'name': u'Multiply integers',
             'widgets': [{'abstract_widget': u'8b20d4ad-c420-4156-973d-48d6d15934ba',
                          'abstract_widget_package': u'base',
                          'inputs': [{'description': u'',
                                      'inner_output': None,
                                      'multi_id': 0,
                                      'name': u'Type your integer',
                                      'options': [],
                                      'order': 1,
                                      'outer_output': None,
                                      'parameter': True,
                                      'parameter_type': u'text',
                                      'pk': 10,
                                      'required': True,
                                      'short_name': u'int',
                                      'value': u'5',
                                      'variable': u'integer'}],
                          'name': u'Create Integer',
                          'outputs': [{'description': u'The returned integer.',
                                       'inner_input': None,
                                       'name': u'Integer',
                                       'order': 1,
                                       'outer_input': None,
                                       'pk': 7,
                                       'short_name': u'int',
                                       'variable': u'integer'}],
                          'save_results': False,
                          'type': u'regular',
                          'workflow': None,
                          'x': 29,
                          'y': 77},
                         {'abstract_widget': u'8b20d4ad-c420-4156-973d-48d6d15934ba',
                          'abstract_widget_package': u'base',
                          'inputs': [{'description': u'',
                                      'inner_output': None,
                                      'multi_id': 0,
                                      'name': u'Type your integer',
                                      'options': [],
                                      'order': 1,
                                      'outer_output': None,
                                      'parameter': True,
                                      'parameter_type': u'text',
                                      'pk': 11,
                                      'required': True,
                                      'short_name': u'int',
                                      'value': u'10',
                                      'variable': u'integer'}],
                          'name': u'Create Integer',
                          'outputs': [{'description': u'The returned integer.',
                                       'inner_input': None,
                                       'name': u'Integer',
                                       'order': 1,
                                       'outer_input': None,
                                       'pk': 8,
                                       'short_name': u'int',
                                       'variable': u'integer'}],
                          'save_results': False,
                          'type': u'regular',
                          'workflow': None,
                          'x': 40,
                          'y': 223},
                         {'abstract_widget': u'8b20d4ad-c420-4156-973d-48d6d15934ba',
                          'abstract_widget_package': u'base',
                          'inputs': [{'description': u'',
                                      'inner_output': None,
                                      'multi_id': 0,
                                      'name': u'Type your integer',
                                      'options': [],
                                      'order': 1,
                                      'outer_output': None,
                                      'parameter': True,
                                      'parameter_type': u'text',
                                      'pk': 12,
                                      'required': True,
                                      'short_name': u'int',
                                      'value': u'5',
                                      'variable': u'integer'}],
                          'name': u'Create Integer',
                          'outputs': [{'description': u'The returned integer.',
                                       'inner_input': None,
                                       'name': u'Integer',
                                       'order': 1,
                                       'outer_input': None,
                                       'pk': 9,
                                       'short_name': u'int',
                                       'variable': u'integer'}],
                          'save_results': False,
                          'type': u'regular',
                          'workflow': None,
                          'x': 39,
                          'y': 364},
                         {'abstract_widget': u'c950af9c-be87-4761-a69e-e37f0c26cacb',
                          'abstract_widget_package': u'base',
                          'inputs': [{'description': u'',
                                      'inner_output': None,
                                      'multi_id': 3,
                                      'name': u'Integers',
                                      'options': [],
                                      'order': 1,
                                      'outer_output': None,
                                      'parameter': False,
                                      'parameter_type': None,
                                      'pk': 13,
                                      'required': False,
                                      'short_name': u'int',
                                      'value': None,
                                      'variable': u'integers'},
                                     {'description': u'',
                                      'inner_output': None,
                                      'multi_id': 3,
                                      'name': u'Integers',
                                      'options': [],
                                      'order': 2,
                                      'outer_output': None,
                                      'parameter': False,
                                      'parameter_type': None,
                                      'pk': 15,
                                      'required': False,
                                      'short_name': u'int',
                                      'value': None,
                                      'variable': u'integers'},
                                     {'description': u'',
                                      'inner_output': None,
                                      'multi_id': 3,
                                      'name': u'Integers',
                                      'options': [],
                                      'order': 3,
                                      'outer_output': None,
                                      'parameter': False,
                                      'parameter_type': None,
                                      'pk': 16,
                                      'required': False,
                                      'short_name': u'int',
                                      'value': None,
                                      'variable': u'integers'},
                                     {'description': u'',
                                      'inner_output': None,
                                      'multi_id': 3,
                                      'name': u'Integers',
                                      'options': [],
                                      'order': 4,
                                      'outer_output': None,
                                      'parameter': False,
                                      'parameter_type': None,
                                      'pk': 65,
                                      'required': False,
                                      'short_name': u'int',
                                      'value': None,
                                      'variable': u'integers'}],
                          'name': u'Multiply integers',
                          'outputs': [{'description': u'',
                                       'inner_input': None,
                                       'name': u'Integer',
                                       'order': 1,
                                       'outer_input': None,
                                       'pk': 10,
                                       'short_name': u'int',
                                       'variable': u'integer'}],
                          'save_results': False,
                          'type': u'regular',
                          'workflow': None,
                          'x': 401,
                          'y': 144},
                         {'abstract_widget': u'2c69b211-05fe-49a2-8de1-d38971e75b95',
                          'abstract_widget_package': u'base',
                          'inputs': [{'description': u'Displays the string so that it is readable.',
                                      'inner_output': None,
                                      'multi_id': 0,
                                      'name': u'String',
                                      'options': [],
                                      'order': 1,
                                      'outer_output': None,
                                      'parameter': False,
                                      'parameter_type': None,
                                      'pk': 14,
                                      'required': False,
                                      'short_name': u'str',
                                      'value': None,
                                      'variable': u'string'}],
                          'name': u'Display String',
                          'outputs': [],
                          'save_results': False,
                          'type': u'regular',
                          'workflow': None,
                          'x': 802,
                          'y': 111},
                         {'abstract_widget': u'1b38bbab-7f89-4469-94cd-2f481f9c61f7',
                          'abstract_widget_package': u'base',
                          'inputs': [{'description': u'',
                                      'inner_output': None,
                                      'multi_id': 0,
                                      'name': u'String',
                                      'options': [],
                                      'order': 1,
                                      'outer_output': None,
                                      'parameter': True,
                                      'parameter_type': u'textarea',
                                      'pk': 51,
                                      'required': False,
                                      'short_name': u'str',
                                      'value': u'balkb blalblab',
                                      'variable': u'string'}],
                          'name': u'Create String',
                          'outputs': [{'description': u'',
                                       'inner_input': None,
                                       'name': u'String',
                                       'order': 1,
                                       'outer_input': None,
                                       'pk': 16,
                                       'short_name': u'str',
                                       'variable': u'string'}],
                          'save_results': False,
                          'type': u'regular',
                          'workflow': None,
                          'x': 272,
                          'y': 408},
                         {'abstract_widget': u'9c8a4da5-6f43-4dbc-846c-adf280c0f484',
                          'abstract_widget_package': u'base',
                          'inputs': [{'description': u'',
                                      'inner_output': None,
                                      'multi_id': 0,
                                      'name': u'String',
                                      'options': [],
                                      'order': 1,
                                      'outer_output': None,
                                      'parameter': False,
                                      'parameter_type': None,
                                      'pk': 52,
                                      'required': False,
                                      'short_name': u'str',
                                      'value': None,
                                      'variable': u'string'}],
                          'name': u'Word cloud',
                          'outputs': [],
                          'save_results': False,
                          'type': u'regular',
                          'workflow': None,
                          'x': 731,
                          'y': 283},
                         {'abstract_widget': None,
                          'inputs': [],
                          'name': u'Untitled widget',
                          'outputs': [{'description': u'',
                                       'inner_input': 79,
                                       'name': u'Output',
                                       'order': 1,
                                       'outer_input': None,
                                       'pk': 23,
                                       'short_name': u'out',
                                       'variable': u'Output26'}],
                          'save_results': False,
                          'type': u'subprocess',
                          'workflow': {'connections': [],
                                       'description': u'',
                                       'name': u'Untitled widget',
                                       'widgets': [{'abstract_widget': None,
                                                    'inputs': [{'description': None,
                                                                'inner_output': None,
                                                                'multi_id': 0,
                                                                'name': u'Output',
                                                                'options': [],
                                                                'order': 1,
                                                                'outer_output': 23,
                                                                'parameter': False,
                                                                'parameter_type': None,
                                                                'pk': 79,
                                                                'required': False,
                                                                'short_name': u'out',
                                                                'value': None,
                                                                'variable': u'Output26'}],
                                                    'name': u'Output',
                                                    'outputs': [],
                                                    'save_results': False,
                                                    'type': u'output',
                                                    'workflow': None,
                                                    'x': 364,
                                                    'y': 236}]},
                          'x': 443,
                          'y': 528},
                         {'abstract_widget': None,
                          'inputs': [],
                          'name': u'Untitled widget',
                          'outputs': [{'description': u'',
                                       'inner_input': 97,
                                       'name': u'Output',
                                       'order': 1,
                                       'outer_input': None,
                                       'pk': 29,
                                       'short_name': u'out',
                                       'variable': u'Output32'}],
                          'save_results': False,
                          'type': u'subprocess',
                          'workflow': {'connections': [],
                                       'description': u'',
                                       'name': u'Untitled widget',
                                       'widgets': [{'abstract_widget': None,
                                                    'inputs': [{'description': None,
                                                                'inner_output': None,
                                                                'multi_id': 0,
                                                                'name': u'Output',
                                                                'options': [],
                                                                'order': 1,
                                                                'outer_output': 29,
                                                                'parameter': False,
                                                                'parameter_type': None,
                                                                'pk': 97,
                                                                'required': False,
                                                                'short_name': u'out',
                                                                'value': None,
                                                                'variable': u'Output32'}],
                                                    'name': u'Output',
                                                    'outputs': [],
                                                    'save_results': False,
                                                    'type': u'output',
                                                    'workflow': None,
                                                    'x': 50,
                                                    'y': 150}]},
                          'x': 696,
                          'y': 417}]}

        self.assertEqual(a, b)
